### ISSUE TITLE
Create embroider branch

### ISSUE THREAD

**Issue by mike-north** [mike-north/ember-octane-workshop#39]
**Stakeholders:** @stefanpenner, @ef4, @rwjblue

This is a non-trivial app built exclusively with the "octane programming model", with some reasonable test coverage. It would serve as a good app for testing/benchmarking Embroider, for the purposes of detecting regressions and benchmarking performance.

**Action Item:** create an `embroider` branch that uses the [embroider build utility](https://github.com/embroider-build/embroider).

**Comment by mike-north** [comment]
Here's the best we can do today

* Steps `{1-19,21}` work well w/ embroider https://github.com/mike-north/ember-octane-workshop/tree/embroider
* Adding `ember-cli-fastboot` on step 20 creates an issue where `package.json` for the fastboot build is not found. This is a known issue https://github.com/embroider-build/embroider/issues/112

```
Error: Couldn't find /var/folders/tl/b0xfqc6139g9q5v70dbbwxbh000qqz/T/broccoli-737607DmHTYqQJb3L/out-254-packager_runner_embroider_webpack/package.json. You may need to update your version of ember-cli-fastboot.
    at EmberApp.readPackageJSON (/Users/mnorth/Development/workshops/ember-octane/node_modules/fastboot/src/ember-app.js:350:13)
    at new EmberApp (/Users/mnorth/Development/workshops/ember-octane/node_modules/fastboot/src/ember-app.js:34:23)
    at FastBoot._buildEmberApp (/Users/mnorth/Development/workshops/ember-octane/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/mnorth/Development/workshops/ember-octane/node_modules/fastboot/src/index.js:52:10)
    at /Users/mnorth/Development/workshops/ember-octane/node_modules/ember-cli-fastboot/index.js:319:29
    at Layer.handle [as handle_request] (/Users/mnorth/Development/workshops/ember-octane/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mnorth/Development/workshops/ember-octane/node_modules/express/lib/router/index.js:317:13)
    at /Users/mnorth/Development/workshops/ember-octane/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/mnorth/Development/workshops/ember-octane/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/mnorth/Development/workshops/ember-octane/node_modules/express/lib/router/index.js:275:10)
```

**Comment by kiwiupover** [comment]
@dnalagatla I think you might know a bit about this.

**Comment by stefanpenner** [comment]
I fastboot + embroider are currently not yet working, two current efforts:

* https://github.com/ember-fastboot/ember-cli-fastboot/pull/727
* https://github.com/embroider-build/embroider/pull/322
